# Generated by Django 5.0.7 on 2024-09-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='CarBrand',
            new_name='brand_name',
        ),
    ]
