# Generated by Django 5.0.7 on 2024-09-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_carbrand_carmodel_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='car_brand_name',
        ),
    ]
