# Generated by Django 5.0.7 on 2024-09-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carbrand_slug_carmodel_description_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='brand_name',
            new_name='car_model',
        ),
    ]
