# Generated by Django 5.0.7 on 2024-09-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_brand_name_carmodel_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
