# Generated by Django 5.0.7 on 2024-09-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_carmodel_car_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
