# Generated by Django 5.0.7 on 2024-09-16 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carmodel_car_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='buyers',
            field=models.ManyToManyField(blank=True, related_name='purchased_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
